import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${inter.className} bg-[#181A2A] text-white`}>
            <Toaster
               position="top-right"
               reverseOrder={false}
            />
            <div className="max-w-screen-lg mx-auto">
               <Navbar />
               {children}
               <Footer />
            </div>
         </body>
      </html>
   );
}
