import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className="font-inter bg-[#181A2A] text-white">
            <div className="max-w-screen-xl mx-auto">
               <Navbar />
               {children}
            </div>
         </body>
      </html>
   );
}
